# Generated by Django 4.2.28 on 2026-05-21 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название типа', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoriums',
            fields=[
                ('number', models.IntegerField(help_text='Номер аудитории', primary_key=True, serialize=False)),
                ('description', models.TextField(default='', help_text='Описание аудитории')),
                ('floor', models.SmallIntegerField(help_text='Номер этажа', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('have_lessons', models.BooleanField(default=False, editable=False)),
                ('auditorium_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditorium_types')),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.TextField(help_text='Аббревиатура', max_length=15, unique=True)),
                ('full_name', models.TextField(help_text='Полное название', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(help_text='Фамилия преподавателя', max_length=255)),
                ('name', models.TextField(help_text='Имя преподавателя', max_length=255)),
                ('patronymic', models.TextField(blank=True, help_text='Отчество преподавателя (если есть)', max_length=255, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер группы')),
                ('group_type', models.SmallIntegerField(blank=True, choices=[(0, 'Бакалавриат'), (1, 'Специалитет'), (2, 'Магистратура'), (3, 'Аспирантура')], default=0, help_text='Бакалавриат, специалитет, магистратура или аспирантура')),
                ('form', models.SmallIntegerField(blank=True, choices=[(0, 'Очное'), (1, 'Заочное'), (2, 'Очно-заочное'), (3, 'Вечернее')], default=0, help_text='Очное, заочное, очно-заочное или вечернее')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название пары', max_length=255)),
                ('assigment', models.ForeignKey(help_text='Прикрепляется запись преподаватель-факультет для этой пары', on_delete=django.db.models.deletion.RESTRICT, to='core.faculty_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.SmallIntegerField(blank=True, choices=[(None, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=None, help_text='Подгруппа', null=True)),
                ('week_day', models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default='1', help_text='Номер дня недели')),
                ('time', models.SmallIntegerField(choices=[(1, '8:20-9:50'), (2, '10:00-11:35'), (3, '12:05-13:40'), (4, '13:50-15:25'), (5, '15:35-17:10'), (6, '17:20-18:40'), (7, '18:45-20:05'), (8, '20:10-21:30')], help_text='Номер пары')),
                ('lesson_type', models.SmallIntegerField(choices=[(0, 'Практика'), (1, 'Лекция'), (2, 'Лабораторная')], default=0, help_text='Практика, лекция или лабораторная')),
                ('parity', models.BooleanField(blank=True, choices=[(None, '-'), (True, 'Числитель'), (False, 'Знаменатель')], default=None, help_text='Числитель или знаменатель', null=True)),
                ('auditorium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditoriums')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Groups_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groups')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessons')),
            ],
        ),
    ]
