# Generated by Django 4.2.28 on 2026-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание аудитории'),
        ),
    ]
