# Generated by Django 4.2.28 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditoriums_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='description',
            field=models.TextField(default='', help_text='Описание аудитории', null=True),
        ),
    ]
