# Generated by Django 4.2.28 on 2026-05-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditoriums_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='auditorium_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditorium_types'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание аудитории', null=True),
        ),
    ]
