# Generated by Django 4.2.28 on 2026-05-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditoriums_auditorium_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_teachers',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.faculties'),
        ),
    ]
