# Generated by Django 4.2.28 on 2026-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_faculty_teachers_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='full_name',
            field=models.TextField(default=None, help_text='Полное название', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='short_name',
            field=models.TextField(blank=True, help_text='Аббревиатура', max_length=15, null=True),
        ),
    ]
