# Generated by Django 4.2.28 on 2026-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_faculties_full_name_alter_faculties_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons_schedule',
            name='lesson_type',
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(0, 'Практика'), (1, 'Лекция'), (2, 'Лабораторная')], default=0, help_text='Практика, лекция или лабораторная'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='short_name',
            field=models.TextField(blank=True, help_text='Аббревиатура (если полное название длинное)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.TextField(help_text='Название пары', max_length=400),
        ),
    ]
