# Generated by Django 4.2.28 on 2026-05-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_lessons_schedule_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='assigment',
            field=models.ForeignKey(blank=True, help_text='Прикрепляется запись преподаватель-факультет для этой пары', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.faculty_teachers'),
        ),
    ]
