# Generated by Django 4.2.28 on 2026-05-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lessons_assigment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorium_types',
            options={'verbose_name': 'Вид аудиторий', 'verbose_name_plural': 'Виды аудиторий'},
        ),
        migrations.AlterModelOptions(
            name='auditoriums',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='faculty_teachers',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groups_schedule',
            options={'verbose_name': 'Расписание по группам', 'verbose_name_plural': 'Расписания по группам'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='lessons_schedule',
            options={'verbose_name': 'Пункт расписания', 'verbose_name_plural': 'Пункты расписания'},
        ),
    ]
