# Generated by Django 4.2.28 on 2026-05-30 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditorium_types_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups_schedule',
            options={'verbose_name': 'Пара по группам', 'verbose_name_plural': 'Пары по группам'},
        ),
        migrations.AlterField(
            model_name='auditorium_types',
            name='name',
            field=models.TextField(help_text='Название типа', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='auditorium_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditorium_types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание аудитории (например, особое название, в честь кого она была названа)', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='floor',
            field=models.SmallIntegerField(help_text='Номер этажа', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='have_lessons',
            field=models.BooleanField(default=False, editable=False, verbose_name='Пары?'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='number',
            field=models.IntegerField(help_text='Номер аудитории', primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='full_name',
            field=models.TextField(default=None, help_text='Полное название', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='short_name',
            field=models.TextField(blank=True, help_text='Аббревиатура (если полное название длинное)', max_length=15, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='faculty_teachers',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='faculty_teachers',
            name='name',
            field=models.TextField(help_text='Имя преподавателя', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='faculty_teachers',
            name='patronymic',
            field=models.TextField(blank=True, help_text='Отчество преподавателя (если есть)', max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='faculty_teachers',
            name='surname',
            field=models.TextField(help_text='Фамилия преподавателя', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='form',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Очное'), (1, 'Заочное'), (2, 'Очно-заочное'), (3, 'Вечернее')], default=0, help_text='Очное, заочное, очно-заочное или вечернее', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Бакалавриат'), (1, 'Специалитет'), (2, 'Магистратура'), (3, 'Аспирантура')], default=0, help_text='Бакалавриат, специалитет, магистратура или аспирантура', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='number',
            field=models.IntegerField(help_text='Номер группы', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessons', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='assigment',
            field=models.ForeignKey(blank=True, help_text='Прикрепляется запись преподаватель-факультет для этой пары', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.faculty_teachers', verbose_name='Назначен'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(0, 'Практика'), (1, 'Лекция'), (2, 'Лабораторная')], default=0, help_text='Практика, лекция или лабораторная', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.TextField(help_text='Название пары', max_length=400, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditoriums', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lessons', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.BooleanField(blank=True, choices=[(None, '-'), (True, 'Числитель'), (False, 'Знаменатель')], default=None, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=None, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='time',
            field=models.SmallIntegerField(choices=[(1, '8:20-9:50'), (2, '10:00-11:35'), (3, '12:05-13:40'), (4, '13:50-15:25'), (5, '15:35-17:10'), (6, '17:20-18:40'), (7, '18:45-20:05'), (8, '20:10-21:30')], help_text='Номер пары', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default='1', help_text='Номер дня недели', verbose_name='День недели'),
        ),
    ]
