# Generated by Django 4.2.28 on 2026-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_groups_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='have_lessons',
            field=models.BooleanField(default=False, editable=False, help_text='Проводятся ли пары в аудитории', verbose_name='Пары?'),
        ),
    ]
