# Generated by Django 4.2.28 on 2026-06-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_auditoriums_have_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='assigment',
            new_name='assignment',
        ),
    ]
