# Generated by Django 4.2.28 on 2026-06-04 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_assigment_lessons_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium_types',
            name='name',
            field=models.TextField(editable=False, help_text='Название типа', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='floor',
            field=models.SmallIntegerField(editable=False, help_text='Номер этажа', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='number',
            field=models.IntegerField(editable=False, help_text='Номер аудитории', primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='full_name',
            field=models.TextField(default=None, editable=False, help_text='Полное название', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='short_name',
            field=models.TextField(blank=True, editable=False, help_text='Аббревиатура (если полное название длинное)', max_length=15, null=True, verbose_name='Аббревиатура'),
        ),
    ]
