# Generated by Django 4.2.28 on 2026-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditorium_types_name_alter_auditoriums_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons_schedule',
            name='comment',
            field=models.TextField(blank=True, default=None, help_text='Комментарий от диспетчера', max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
