# Generated by Django 4.2.28 on 2026-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lessons_schedule_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('number', 'faculty'), name='unique_group_number_per_faculty'),
        ),
    ]
