# Generated by Django 4.2.28 on 2026-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_groups_unique_group_number_per_faculty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groups',
            name='unique_group_number_per_faculty',
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('number', 'group_type', 'form', 'faculty'), name='unique_group_per_faculty'),
        ),
    ]
