# Generated by Django 4.2.28 on 2026-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_groups_unique_group_number_per_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='form',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Очное'), (2, 'Заочное'), (3, 'Очно-заочное'), (4, 'Вечернее')], default=0, help_text='Очное, заочное, очно-заочное или вечернее', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Бакалавриат'), (2, 'Специалитет'), (3, 'Магистратура'), (4, 'Аспирантура')], default=0, help_text='Бакалавриат, специалитет, магистратура или аспирантура', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(1, 'Практика'), (2, 'Лекция'), (3, 'Лабораторная')], default=0, help_text='Практика, лекция или лабораторная', verbose_name='Тип'),
        ),
    ]
