# Generated by Django 4.2.28 on 2026-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_groups_form_alter_groups_group_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faculty_teachers',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic', 'faculty'), name='unique_teacher_per_faculty'),
        ),
    ]
