# Generated by Django 4.2.28 on 2026-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_faculty_teachers_unique_teacher_per_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ('name',), 'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AddConstraint(
            model_name='groups_schedule',
            constraint=models.UniqueConstraint(fields=('group', 'lesson'), name='unique_lesson_per_group'),
        ),
    ]
