# Generated by Django 4.2.28 on 2026-06-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_schedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.groups_schedule', verbose_name='Пара'),
        ),
    ]
