# Generated by Django 4.2.28 on 2026-06-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_lessons_schedule_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriums',
            options={'ordering': ('number',), 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ('number',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='auditorium_type',
            field=models.ForeignKey(blank=True, help_text='Лекционная аудитория, компьютерных класс и т.п.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditorium_types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='faculty_teachers',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Выберите из существующих', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='faculty',
            field=models.ForeignKey(help_text='Выберите их существующих', on_delete=django.db.models.deletion.RESTRICT, to='core.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='number',
            field=models.IntegerField(help_text='Обычно трёхзначное число', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='group',
            field=models.ForeignKey(help_text='Обычно трёхзначное число', on_delete=django.db.models.deletion.CASCADE, to='core.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='lesson',
            field=models.ForeignKey(help_text='Обычно трёхзначное число', on_delete=django.db.models.deletion.CASCADE, to='core.lessons', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='auditorium',
            field=models.ForeignKey(help_text='Аудитория, в которой пара проводится', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditoriums', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='lesson',
            field=models.ForeignKey(help_text='Запись Пара-Группа', on_delete=django.db.models.deletion.RESTRICT, to='core.groups_schedule', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(1, '-'), (2, 'Числитель'), (3, 'Знаменатель')], default=None, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
    ]
