# Generated by Django 4.2.28 on 2026-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_auditoriums_options_alter_groups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=None, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
    ]
