# Generated by Django 4.2.28 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lessons_schedule_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, '-'), (1, 'Числитель'), (2, 'Знаменатель')], default=0, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='time',
            field=models.SmallIntegerField(choices=[(1, '8:20-9:50'), (2, '10:00-11:35'), (3, '12:05-13:40'), (4, '13:50-15:25'), (5, '15:35-17:10'), (6, '17:20-18:40'), (7, '18:45-20:05'), (8, '20:10-21:30')], help_text='Время проведения пары', verbose_name='Время'),
        ),
    ]
