# Generated by Django 4.2.28 on 2026-06-14 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_lessons_schedule_parity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='floor',
            field=models.SmallIntegerField(help_text='Номер этажа', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='number',
            field=models.IntegerField(help_text='Номер аудитории', primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], default=0, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=0, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], help_text='Номер дня недели', verbose_name='День недели'),
        ),
    ]
