# Generated by Django 4.2.28 on 2026-06-14 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_auditoriums_floor_alter_auditoriums_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='floor',
            field=models.SmallIntegerField(editable=False, help_text='Номер этажа', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='auditoriums',
            name='number',
            field=models.IntegerField(editable=False, help_text='Номер аудитории', primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], default=0, help_text='Числитель или знаменатель', verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=0, help_text='Подгруппа', verbose_name='Подгруппа'),
        ),
    ]
