# Generated by Django 4.2.28 on 2026-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_auditoriums_floor_alter_auditoriums_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
    ]
