# Generated by Django 4.2.28 on 2026-06-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_lessons_schedule_parity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Практика'), (2, 'Лекция'), (3, 'Лабораторная')], default=0, help_text='Практика, лекция или лабораторная', null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], default=0, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=0, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
    ]
