# Generated by Django 4.2.28 on 2026-06-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_lessons_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriums',
            name='auditorium_type',
            field=models.ForeignKey(blank=True, help_text='Лекционная аудитория, компьютерный класс и т.п.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditorium_types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='faculty',
            field=models.ForeignKey(help_text='Выберите из существующих', on_delete=django.db.models.deletion.RESTRICT, to='core.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='group',
            field=models.ForeignKey(help_text='Выберите из существующих записей', on_delete=django.db.models.deletion.CASCADE, to='core.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groups_schedule',
            name='lesson',
            field=models.ForeignKey(help_text='Выберите из существующих записей', on_delete=django.db.models.deletion.CASCADE, to='core.lessons', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Практика'), (2, 'Лекция'), (3, 'Лабораторная')], default=None, help_text='Практика, лекция или лабораторная', null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий от диспетчера', max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], default=None, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], default=None, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], help_text='День недели', verbose_name='День недели'),
        ),
    ]
