# Generated by Django 4.2.28 on 2026-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_auditoriums_auditorium_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='form',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Очное'), (2, 'Заочное'), (3, 'Очно-заочное'), (4, 'Вечернее')], default=0, help_text='Очное, заочное, очно-заочное или вечернее', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Бакалавриат'), (2, 'Специалитет'), (3, 'Магистратура'), (4, 'Аспирантура')], default=0, help_text='Бакалавриат, специалитет, магистратура или аспирантура', verbose_name='Вид'),
        ),
    ]
