# Generated by Django 4.2.28 on 2026-06-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_groups_form_alter_groups_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_schedule',
            name='comment',
            field=models.TextField(blank=True, db_index=True, help_text='Комментарий от диспетчера', max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='parity',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'нет'), (1, 'Числитель'), (2, 'Знаменатель')], db_index=True, default=None, help_text='Числитель или знаменатель', null=True, verbose_name='Чётность'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='subgroup',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вся группа'), (1, '1'), (2, '2'), (3, '3')], db_index=True, default=None, help_text='Подгруппа', null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='time',
            field=models.SmallIntegerField(choices=[(1, '8:20-9:50'), (2, '10:00-11:35'), (3, '12:05-13:40'), (4, '13:50-15:25'), (5, '15:35-17:10'), (6, '17:20-18:40'), (7, '18:45-20:05'), (8, '20:10-21:30')], db_index=True, help_text='Время проведения пары', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='lessons_schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], db_index=True, help_text='День недели', verbose_name='День недели'),
        ),
    ]
